filebeat.inputs:
  - type: filestream
    enabled: true
    paths:
      - /usr/share/filebeat/logs/*.log  # app_logs 볼륨에서 마운트된 경로
    fields:
      service: spring-app
    multiline:
      pattern: '^\d{4}-\d{2}-\d{2}'  # 로그 시작이 날짜일 경우
      negate: true
      match: after

output.logstash:
  hosts: ["logstash:5044"]
