networks:
  elk_monitoring:
    external: true

volumes:
  grafana_agent_data:   # Agent WAL
  k6_scripts:           # k6 시나리오

services:
  grafana-agent:
    image: grafana/agent:v0.43.0
    container_name: grafana-agent-k6
    ports:
      - "12345:12345"
    command: >
      --config.file=/etc/agent/agent.yml
    volumes:
      - ./grafana-agent/agent.yml:/etc/agent/agent.yml:ro
      - grafana_agent_data:/var/lib/grafana-agent/data
    networks: [ elk_monitoring ]
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:12345/-/ready || exit 1"]
      interval: 20s
      timeout : 5s
      retries : 5

  k6:
    image: grafana/k6:0.57
    container_name: k6-runner
    depends_on:
      grafana-agent:
        condition: service_healthy
    entrypoint: >
      k6 run /scripts/loadtest.js
      --tag project=garabu
      --out experimental-prometheus-rw,http://grafana-agent:12345/api/v1/write
    environment:
      - TARGET_URL=http://spring-app:8080/actuator/health
      - K6_PROMETHEUS_RW_TREND_STATS=p(50),p(90),p(95),p(99),min,max,avg
    volumes:
      - ./k6-scripts:/scripts:ro
    networks: [ elk_monitoring ]
