groups:
  - name: example-alert
    rules:
      - alert: HighHttpRequestRate
        expr: rate(http_server_requests_seconds_count[1m]) > 5
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "높은 HTTP 요청 수"
          description: "1분 동안 평균 요청 수가 5를 초과했습니다."
