apiVersion: v1
kind: ConfigMap
metadata:
  name: garabu-app-config
  namespace: garabu
data:
  application-prod.yml: |
    spring:
      datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        hikari:
          maximum-pool-size: 30
          minimum-idle: 10
          connection-timeout: 30000
          idle-timeout: 600000
          max-lifetime: 1800000
      
      redis:
        host: ${SPRING_REDIS_HOST}
        port: ${SPRING_REDIS_PORT}
        password: ${SPRING_REDIS_PASSWORD}
        lettuce:
          pool:
            max-active: 10
            max-idle: 10
            min-idle: 5
      
      security:
        oauth2:
          client:
            registration:
              google:
                client-id: 392078217032-kp4d65bonfieldsjo2umnkt7k6nfjj0e.apps.googleusercontent.com
                client-secret: ${GOOGLE_CLIENT_SECRET}
                scope: profile,email
                redirect-uri: https://api.garabu.com/login/oauth2/code/google
              naver:
                client-id: ATIv9Qw4E9KcYxW6IpMA
                client-secret: ${NAVER_CLIENT_SECRET}
                redirect-uri: https://api.garabu.com/login/oauth2/code/naver
                authorization-grant-type: authorization_code
                scope: name,email
              apple:
                client-id: com.popori99.garabuapp2
                client-secret: ${APPLE_CLIENT_SECRET}
                redirect-uri: https://api.garabu.com/login/oauth2/code/apple
                authorization-grant-type: authorization_code
                scope: name,email
      
      jpa:
        hibernate:
          ddl-auto: validate
        properties:
          hibernate:
            format_sql: false
            show_sql: false
            dialect: org.hibernate.dialect.MySQL8Dialect
    
    cors:
      allowed-origins:
        - https://garabu.com
        - https://www.garabu.com
        - https://app.garabu.com
      timeout: 6000
    
    jwt:
      header: Authorization
      secret: ${JWT_SECRET}
      token-validity-in-seconds: 86400
    
    logging:
      level:
        root: INFO
        garabu.garabuServer: INFO
        org.springframework.web: INFO
        org.springframework.security: WARN
        org.hibernate.SQL: WARN
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    
    management:
      endpoints:
        web:
          exposure:
            include: health,info,prometheus
      endpoint:
        health:
          show-details: when-authorized
        prometheus:
          enabled: true
      metrics:
        export:
          prometheus:
            enabled: true
    
    notification:
      provider: expo
      expo:
        enabled: true