apiVersion: v1
kind: Secret
metadata:
  name: firebase-admin-key
  namespace: garabu
type: Opaque
data:
  # Firebase Admin SDK JSON 파일을 base64로 인코딩해서 넣어야 합니다
  # cat garabu-d95ea-firebase-adminsdk-fbsvc-435a13aff1.json | base64 -w 0
  firebase-adminsdk.json: |
    YOUR_BASE64_ENCODED_FIREBASE_ADMIN_SDK_JSON