# This is the root kustomization file
# Use overlays/production/kustomization.yaml for production deployment
# Use overlays/development/kustomization.yaml for development deployment

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - networkpolicy.yaml

# Use the appropriate overlay for your environment:
# kubectl apply -k overlays/production/
# kubectl apply -k overlays/development/