apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: garabu-server-pdb
  namespace: garabu
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: garabu-server
  maxUnavailable: 1