apiVersion: v1
kind: ServiceAccount
metadata:
  name: garabu-server
  namespace: garabu
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::YOUR-ACCOUNT-ID:role/garabu-server-eks-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: garabu-server-role
  namespace: garabu
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: garabu-server-rolebinding
  namespace: garabu
subjects:
- kind: ServiceAccount
  name: garabu-server
  namespace: garabu
roleRef:
  kind: Role
  name: garabu-server-role
  apiGroup: rbac.authorization.k8s.io